### ISSUE TITLE
Add Case test fails

### ISSUE THREAD

**Issue by paddatrapper** [paddatrapper/CaseTracker#36]
<s>Not sure the direct cause</s>, but the add case test fails after a few runs. Flushing the db fixes the issue

**Comment by paddatrapper** [comment]
Turns out it is caused by a MySQL Database Truncation error as case number is too long:

```
21:07:10 [Thread-7 ERROR c.k.c.s.datalayer.CaseRepository - Error inserting case 2015-07-00010 - Something happened
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'caseNumber' at row 1
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3885) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.kritsit.casetracker.server.datalayer.DatabasePersistence.set(DatabasePersistence.java:134) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.kritsit.casetracker.server.datalayer.DatabasePersistence.executeUpdate(DatabasePersistence.java:119) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.kritsit.casetracker.server.datalayer.CaseRepository.insertCase(CaseRepository.java:167) ~[server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at com.kritsit.casetracker.server.domain.services.ClientConnectionThread.run(ClientConnectionThread.java:100) [server-0.1a-SNAPSHOT-jar-with-dependencies.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```
